### ISSUE TITLE
None.get exception when trying to markDelete root infoton

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#252]
Following example:
```
curl -X POST "cm-well-uk-lab.int.thomsonreuters.com/_in?format=turtle" --data-binary '
@prefix sys:   <http://cm-well-uk-lab.int.thomsonreuters.com/meta/sys#> .
<http://cm-well-uk-lab.int.thomsonreuters.com>
<cmwell://meta/sys#markDelete> [
        sys:path          "/" ;
        sys:type          "ObjectInfoton" ;
  ]
'
```
Fails with  none.get exception:
```
2017-10-24 11:54:22,024 [ForkJoinPool-1-worker-15]                   ERROR wsutil.package$                      - unexpected error occurred                                                                    │
java.util.NoSuchElementException: None.get                                                                                                                                                                     │
        at scala.None$.get(Option.scala:347)                                                                                                                                                                   │
        at scala.None$.get(Option.scala:345)                                                                                                                                                                   │
        at cmwell.web.ld.util.LDFormatParser$$anonfun$updateDeleteValuesMap$1.apply(LDFormatParser.scala:740)                                                                                                  │
        at cmwell.web.ld.util.LDFormatParser$$anonfun$updateDeleteValuesMap$1.apply(LDFormatParser.scala:738)                                                                                                  │
        at scala.collection.immutable.List.foreach(List.scala:392)                                                                                                                                             │
        at cmwell.web.ld.util.LDFormatParser$.updateDeleteValuesMap(LDFormatParser.scala:738)                                                                                                                  │
        at cmwell.web.ld.util.LDFormatParser$$anonfun$21.apply(LDFormatParser.scala:637)                                                                                                                       │
        at cmwell.web.ld.util.LDFormatParser$$anonfun$21.apply(LDFormatParser.scala:510)                                                                                                                       ┤
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)                                                                                                                    │
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)                                                                                                                    │
        at scala.collection.immutable.List.foreach(List.scala:392)                                                                                                                                             │
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)                                                                                                                               │
        at scala.collection.immutable.List.map(List.scala:296)                                                                                                                                                 │
        at cmwell.web.ld.util.LDFormatParser$.rdfToInfotonsMap(LDFormatParser.scala:510)                                                                                                                       │
        at cmwell.web.ld.service.WriteService$.handleFormatByFormatParameter(WriteService.scala:54)                                                                                                            │
        at controllers.InputHandler.controllers$InputHandler$$parseRDF(InputHandler.scala:172)                                                                                                                 │
        at controllers.InputHandler$$anonfun$handlePostRDF$2.apply(InputHandler.scala:237)                                                                                                                     │
        at controllers.InputHandler$$anonfun$handlePostRDF$2.apply(InputHandler.scala:415)                                                                                                                     │
        at scala.util.Try$.apply(Try.scala:192)                                                                                                                                                                │
        at controllers.InputHandler.handlePostRDF(InputHandler.scala:236)                                                                                                                                      │
        at controllers.InputHandler$$anonfun$handlePost$1.apply(InputHandler.scala:71)                                                                                                                         │
        at controllers.InputHandler$$anonfun$handlePost$1.apply(InputHandler.scala:65)                                                                                                                         │
        at controllers.IngestPushback$$anonfun$controllers$IngestPushback$$resOptToFilterBy$1$1.apply(IngestPushback.scala:113)                                                                                │
        at controllers.IngestPushback$$anonfun$controllers$IngestPushback$$resOptToFilterBy$1$1.apply(IngestPushback.scala:113)                                                                                │
        at scala.Option.fold(Option.scala:158)                                                                                                                                                                 ┤
        at controllers.IngestPushback.controllers$IngestPushback$$resOptToFilterBy$1(IngestPushback.scala:113)                                                                                                 │
        at controllers.IngestPushback$$anonfun$invokeBlock$1.apply(IngestPushback.scala:124)                                                                                                                   │
        at controllers.IngestPushback$$anonfun$invokeBlock$1.apply(IngestPushback.scala:124)                                                                                                                   │
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)                                                                                                                                  │
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)                                                                                                                                  │
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)                                                                                                                                        │
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)                                                                                                                │
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)                                                                                                │
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)                                                                                                       │
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)                                                                                                       │
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)                                                                                                                              │
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)                                                                                                                        │
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)                                                                                                                                       │
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)                                                                                             │
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                                                                                                                   │
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                                                                                                                       │
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                                                                                                               │
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)                
```

Yaakov asked to attach you the following link as well:
https://github.com/thomsonreuters/CM-Well/blob/master/server/cmwell-ws/app/ld/util/LDFormatParser.scala#L740

**Comment by yanpom** [comment]
When fix, to check MarkDelete of root infoton

**Comment by GuyGuterman** [comment]
Tested and validated Response:

`{"success":false,"error":"requirement failed: sys fields not allowed for markDelete failed for: [cmwell://meta/sys#type]"}`

Moving to Done.
