### ISSUE TITLE
STP -Engine Entity stream truncation error during bulk consume

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#387]
Start sparql. see agent.log in DEBUG mode
During the work of getting tsvs with bulk consume following exception is received:
```
2018-01-08 13:26:09,398 -well-egl1-akka.actor.default-dispatcher-96] INFO  or [personperson-legal-professional] - error: Entity stream truncation consumer will perform retry in 1 second, token=cQD4eJy1jL0KwjAURl_GSWySG4zSbgURXNRdHEJ6QwP5I7kOSh7e6uzqmT4OHwe2-15JJRTIftf4pEkzmlOoKRZ8EJbKTAoNxJd2W9MzI1v51xmO4zAT5YHzjCl7DLouf1bN_JnMuqijcdr_6HEpQHQAnQB-XVyKp1jdhGXzr_7FWmewHFxBQ6nc31AWVrg
akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
	at akka.stream.impl.fusing.Collect$$anon$2.$anonfun$wrappedPf$1(Ops.scala:212)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:173)
	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:214)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nicklester** [comment]
Discussed issue with @yanpom this morning. Seems to be an issue affecting the agent, but not the stand alone STP. Have got what is needed to reproduce the issue and will investigate.

**Comment by e-orz** [comment]
Try it from the same location the agent is run from. Might be related to network/firewalls.

**Comment by YoniMataraso** [comment]
Let's revisit after we move to consume.
