### ISSUE TITLE
STP - oafull sparql fail to be readed by cm-well

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#389]
Ingest oafull sparql which is working properly standalone, and open agents.log
Following exception appears:
```
2018-01-09 10:17:37,071 [scala-execution-context-global-256784]      WARN  c.t.d.sparql.SparqlProcessorManager  - Reading the config infotons failed. It will be checked on the next schedule check. The exception was:
org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found BlockMappingStart
 in 'string', line 11, column 3:
      prefix tr-org: <http://permid.or ...
      ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:224)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
        at net.jcazevedo.moultingyaml.package$PimpedString$.parseYaml$extension(package.scala:64)
        at cmwell.tools.data.sparql.SparqlProcessorManager.yamlToConfig(SparqlProcessorManager.scala:435)
        at cmwell.tools.data.sparql.SparqlProcessorManager.$anonfun$parseJobsJson$1(SparqlProcessorManager.scala:400)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at cmwell.tools.data.sparql.SparqlProcessorManager.parseJobsJson(SparqlProcessorManager.scala:405)
        at cmwell.tools.data.sparql.SparqlProcessorManager.$anonfun$getJobConfigsFromTheUser$2(SparqlProcessorManager.scala:378)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by yanpom** [comment]
Not bug
