### ISSUE TITLE
STP - config infoton json failed to be parsed

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#404]
No agents are running
Following exception appeared in agents.log
```
2018-01-18 13:42:06,387 [scala-execution-context-global-328]         WARN  c.t.d.sparql.SparqlProcessorManager  - The manager failed to parse the json of the config infotons failed with exception! The json was: {
  "success" : false,
  "error" : "Failed to execute phase [fetch], [reduce] "
}
2018-01-18 13:42:06,387 [scala-execution-context-global-328]         WARN  c.t.d.sparql.SparqlProcessorManager  - Reading the config infotons failed. It will be checked on the next schedule check. The exception was:
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at cmwell.tools.data.sparql.SparqlProcessorManager.parseJobsJson(SparqlProcessorManager.scala:396)
        at cmwell.tools.data.sparql.SparqlProcessorManager.$anonfun$getJobConfigsFromTheUser$2(SparqlProcessorManager.scala:378)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2018-01-18 13:42:06,389 -well-egl1-akka.actor.default-dispatcher-63] WARN  c.t.d.sparql.SparqlProcessorManager  - Received Status failure
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at cmwell.tools.data.sparql.SparqlProcessorManager.parseJobsJson(SparqlProcessorManager.scala:396)
        at cmwell.tools.data.sparql.SparqlProcessorManager.$anonfun$getJobConfigsFromTheUser$2(SparqlProcessorManager.scala:378)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by e-orz** [comment]
The parser is very restrictive. Everything that is not accepted will cause a parse error.
It may be inproved, of course. But this API is for the maintainers that should know what they are doing.

**Comment by e-orz** [comment]
Just talked to @hochgi This is a failed response from ES. They code can be improve to print also the full HttpResponse instead of just the response of the JSON. This way we will be able to analyse the ws that replied with the response.

**Comment by YoniMataraso** [comment]
Thanks @e-orz , can we add this as a new task for @nicklester please

**Comment by yanpom** [comment]
Verified and closed
