### ISSUE TITLE
STP - Lot of 503 service Unavaliable warnings when adding new agent

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#413]
Have some agents running on the system:
person
tmpp
oafull
lbd
symric
typerdf
Create new one - industry
Monitor agent.log

Lot of 503 service unavailable warnings appear in the log
2018-01-23 13:28:12,804 -well-egl1-akka.actor.default-dispatcher-57] WARN  cmwell.tools.data.utils.akka.Retry$  - [oafulloa-address] server error: will retry again in 30 seconds host=Some(X-CMWELL-Hostname: c947arhcedn10.int.thomsonreuters.com) status=503 Service Unavailable entity=HttpEntity.Strict(text/plain; charset=UTF-8,Busy, try again later)

After few seconds system stabilized

**Comment by YoniMataraso** [comment]
We will revisit after the move to consume, as it might be related.

**Comment by yanpom** [comment]
Same errors after change to consume

**Comment by nicklester** [comment]
Is this linked to #388, explaining why not all sensors were showing?

**Comment by yanpom** [comment]
There are still 503 exceptions during infoton downloading from source
```
2018-02-12 09:56:38,367 [scala-execution-context-global-100]         ERROR cmwell.tools.data.utils.akka.Retry$  - [dealsjvscore-sparql-materializer] error in consuming data bytes from response, paths=/data.thomsonreuters.com/1-34391901916, err=akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
        at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
        at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
        at akka.stream.impl.fusing.Collect$$anon$2.$anonfun$wrappedPf$1(Ops.scala:213)
        at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:174)
        at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:215)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nicklester** [comment]
STP always recovers from the issue, and the issue is caused by an API call and should be looked at separately.. @yanpom - agree?

**Comment by yanpom** [comment]
yes
