### ISSUE TITLE
streaming infotons fail mid-flight

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#436]
On version with git-commit-hash b55c96bcb0d73d4509b9b92573a7165e97f65710 deployed, streams of 4.5-7M infotons fail during transmission. 

The command:
`curl -v '<<<CMWellHost>>>/?op=stream&recursive&qp=type.rdf::http://<<<legitimateRDFType>>>&format=tsv&debug-log' -o RDFType.tsv`
Curl prints this error 
`curl: (18) transfer closed with outstanding read data remaining`
In the ws/application.log of the node (inferred from response header) we see several of those exceptions in the time of disconnect:
```
2018-01-25 12:11:46,666 [scala-execution-context-global-1092]        ERROR cmwell.web.ld.cmw.CMWellRDFHelper    - getHashForPrefixAsync for organization failed             │
java.util.concurrent.TimeoutException: Operation timed out after 10000 millis                                                                                               │
        at cmwell.fts.FTSServiceNew$TimeoutScheduler$$anon$5.run(FTSServiceNew.scala:1237)                                                                                  │
        at org.elasticsearch.common.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)                                                        │
        at org.elasticsearch.common.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)                                                 │
        at org.elasticsearch.common.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)                                                                       │
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)                                                                  │
        at java.lang.Thread.run(Thread.java:745)     ```

**Comment by Ivan-Shestakov** [comment]
A later update - this happens also when working directly with node, bypassing all load balancers.

**Comment by e-orz** [comment]
That is our known stream issue.

1. We somehow buffer ES response too much and for 1 minutes not getting any more data from it.
2. ES closes the scroll
3. On next data request from ES we are getting and error - the scroll is already closed.
4. We don't parse the error correctly and "think" that ES tells us that there are no more elements.
5. Instead of closing the stream (which was wrong anyway due to the fact that not all the data got from ES) we are sending an empty element for the stream.
6. Empty element to Play stream is not allowed and the stream is closed without sending the last 0 length chunk
7. For the client it's premature EOF

One of the hardest bugs we have. We will need quite an amount of time to debug/understand it.

**Comment by hochgi** [comment]
not accurate.
you were referring to #125 which simply increased TTL to ES to 1h.

op=stream still fails, but after adding `debug-log` which adds `StreamEventInspector` on the ES source and play's sink:
https://github.com/thomsonreuters/CM-Well/blob/master/server/cmwell-util/src/main/scala/cmwell/util/stream/StreamEventInspector.scala
we saw that stream is finished from DOWNSTREAM!

i.e: connection was cut off amid by something else. Not related to ES or the stream engine at all.
I'm still investigating if the problem lies within CM-Well, or perhaps it's a network issue of some sort.
