### ISSUE TITLE
STP Engine - Industry sparql getting stuck when working vs prod environment

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#444]
Egl1 - configure the system to work with prod
create industry infoton which suppose to take data from prod and materialize it on egl1 permid.org
After agent created, 150 infoton pulled in 1:30 minutes. Then no new data was pulled for 20 minutes.
I paused the agent and after a minute resumed it.
Several additional infotons were pulled from prod and work again stopped
Following exception appears in agent.log during the agent work:
```
2018-01-28 15:02:21,437 -well-egl1-akka.actor.default-dispatcher-23] INFO  BufferFillerActor [industryindustry] - received consume answer from host=c053wmjcend06.int.thomsonreuters.com status=503 Service Unavailable token=XwCCeJwzNDU0MzYztjQ3N7Q0r9FPSSxJ1CvJyM8tzs8rSi0tSS0q1kvOz60pqSxI1VPJqfIzdHO0ssooKSmw0ocoLk7OSM1NLNZLy8xLzEvOTMzBol0_N7UkEaRa38jAwFIXhAz1PfNSSotLiioBYJ8tNw entity=�V*.MNN-.V�JK�)N�QJ-*�/R�R�/H-J,���S(��MMQ�/-QHL+I-R04��̜��b�Z��<�۲B
2018-01-28 15:02:21,438 -well-egl1-akka.actor.default-dispatcher-43] INFO  BufferFillerActor [industryindustry] - error: Status is 503 Service Unavailable consumer will perform retry in 1 second, token=XwCCeJwzNDU0MzYztjQ3N7Q0r9FPSSxJ1CvJyM8tzs8rSi0tSS0q1kvOz60pqSxI1VPJqfIzdHO0ssooKSmw0ocoLk7OSM1NLNZLy8xLzEvOTMzBol0_N7UkEaRa38jAwFIXhAz1PfNSSotLiioBYJ8tNw
java.lang.Exception: Status is 503 Service Unavailable
        at cmwell.tools.data.downloader.consumer.BufferFillerActor.$anonfun$sendNextChunkRequest$5(BufferFillerActor.scala:261)
        at akka.stream.impl.fusing.Map$$anon$8.onPush(Ops.scala:48)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nicklester** [comment]
The BufferFiller should catch this 503 and re-try one second later, and this is the behaviour I observed when reproducing the issue locally. 

@yanpom @YoniMataraso Maybe one second re-try is a little brutal - should we slow this down?

**Comment by nicklester** [comment]
@e-orz - do you have any opinion on the retry rate mentioned above?

**Comment by yanpom** [comment]
Currently, there are still 503 errors which appear frequently but the progress continues and doesnt stuck
So this concrete issue can be closed, because we have different issue for 503 errors
