### ISSUE TITLE
An error message and response is not clear when ingest empty predicate

### ISSUE THREAD

**Issue by GuyGuterman** [thomsonreuters/CM-Well#554]
Ingest infoton with empty predicate, ```response 500``` and message: ```"error": "next on empty iterator"```

**Comment by hochgi** [comment]
relevant stack trace (for `curl -svX POST 'http://cm-well/_in?format=ntriples' --data-binary '<http://test.test/Path/Path/Path> <> "55" .'`):
```
2018-03-22 09:53:58,656 [scala-execution-context-global-399]         ERROR wsutil.package$                      - unexpected error occurred
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:38)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:36)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:60)
        at scala.collection.IterableLike.head(IterableLike.scala:106)
        at scala.collection.IterableLike.head$(IterableLike.scala:105)
        at scala.collection.immutable.StringOps.scala$collection$IndexedSeqOptimized$$super$head(StringOps.scala:29)
        at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:125)
        at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:125)
        at scala.collection.immutable.StringOps.head(StringOps.scala:29)
        at cmwell.web.ld.util.LDFormatParser$.inferShortNameFromUrl(LDFormatParser.scala:926)
        at cmwell.web.ld.util.LDFormatParser$$anonfun$5.$anonfun$applyOrElse$1(LDFormatParser.scala:877)
        at scala.collection.MapLike.getOrElse(MapLike.scala:128)
        at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
        at scala.collection.AbstractMap.getOrElse(Map.scala:59)
        at cmwell.web.ld.util.LDFormatParser$$anonfun$5.applyOrElse(LDFormatParser.scala:877)
        at cmwell.web.ld.util.LDFormatParser$$anonfun$5.applyOrElse(LDFormatParser.scala:876)
        at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:141)
        at scala.collection.immutable.Stream.collect(Stream.scala:432)
        at cmwell.web.ld.util.LDFormatParser$.convertMetaMapToInfotonFormatMap(LDFormatParser.scala:876)
        at cmwell.web.ld.util.LDFormatParser$.modelsFromRdfDataInputStream(LDFormatParser.scala:456)
        at cmwell.web.ld.util.LDFormatParser$.rdfToInfotonsMap(LDFormatParser.scala:524)
        at cmwell.web.ld.service.WriteService$.handleFormatByFormatParameter(WriteService.scala:53)
        at controllers.InputHandler.parseRDF(InputHandler.scala:204)
        at controllers.InputHandler.$anonfun$handlePostRDF$2(InputHandler.scala:283)
        at scala.util.Try$.apply(Try.scala:209)
        at controllers.InputHandler.handlePostRDF(InputHandler.scala:463)
        at controllers.InputHandler.$anonfun$handlePost$1(InputHandler.scala:72)
        at controllers.IngestPushback.$anonfun$invokeBlock$1(IngestPushback.scala:91)
        at scala.Option.fold(Option.scala:158)
        at controllers.IngestPushback.resOptToFilterBy$1(IngestPushback.scala:91)
        at controllers.IngestPushback.$anonfun$invokeBlock$6(IngestPushback.scala:102)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
