### ISSUE TITLE
add_node script fails 

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#596]
### Add node fails
On cmwell environment with missing node, add node operation fails.

### Steps taken: 
* Stop all cmwell processes and wait 15 minutes 
* Verify that health-detailed shows n-1 nodes.
* In folder with installation package have ready a custom json file with this content:
```javascript
[
{"ip":"11.111.111.111", "mappings":["192.168.111.121","192.168.111.122","192.168.111.123","192.168.111.124"]}
]
```
* Execute the `add_node cmw.env_11.111.111.111` command.

* Expected: all processes up and running. Health-detailed.md shows N nodes.
* Actual: NPE in script output. No cmwell processes up.

The command line output is:  
 ```
WARNING: 11.111.111.111 Will be added to CM-Well grid!!!
Continue?
If YES, write: YeS and press Enter
YeS
current cm-well environment is /clfmnt/data/cmwell
ping: Warning: source address might be selected on device other than lo.
Info: Connecting to grid with ip: 127.0.0.1
This is a production cluster. Are you sure you want to do this operation: (yes/no)
yes
Info: purging cm-well
Info:   stopping processes
Info:   clearing application data
Info:   clearing data
Info: finished purging cm-well
This is a production cluster. Are you sure you want to do this operation: (yes/no)
yes
Info: deploying application
Info:   creating application directories
Info:   deploying components
Info:   creating symbolic links
Info:   linking cassandra data directories
Info:   linking elasticsearch data directories
Info:   linking zookeeper data directories
Info:   linking kafka data directories
Info:   linking cmwell-batch data directories
Info:   creating cassandra log directories
Info:   creating elasticsearch log directories
Info:   creating zookeeper log directories
Info:   creating kafka log directories
Info:   creating cmwell-bg log directories
Info:   creating cmwell-batch log directories
Info:   creating cmwell-ws log directories
Info:   creating cmwell-controller log directories
Info:   creating cmwell-dc log directories
Info:   creating cassandra configuration directories
Info:   creating elasticsearch configuration directories
Info:   creating zookeeper configuration directories
Info:   creating kafka configuration directories
Info:   creating cmwell-bg configuration directories
Info:   creating cmwell-ws configuration directories
Info:   creating cmwell-controller configuration directories
Info:   creating links in app directory
Info:   creating scripts
Info:   deploying plugins
Info:   linking libs
Info: finished deploying application
java.lang.NullPointerException
       at cmwell.ctrl.client.CtrlClient$.addNode(CtrlClient.scala:165)
       at Host.$anonfun$addNodes$3(ctl.scala:1253) ```

**Comment by e-orz** [comment]
This is a Grid issue:
from logs in TRACE:
2018-03-25 13:47:33,473 ell-mc-ppe-akka.actor.default-dispatcher-19] WARN  a.r.transport.netty.NettyTransport   - Remote connection to [null] failed with java.net.ConnectException: Connection refused: /10.205.159.43:0
2018-03-25 13:47:33,473 ell-mc-ppe-akka.actor.default-dispatcher-19] WARN  a.remote.ReliableDeliverySupervisor  - Association with remote system [akka.tcp://cm-well-mc-ppe@10.205.159.43:0] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://cm-well-mc-ppe@10.205.159.43:0]] Caused by: [Connection refused: /10.205.159.43:0]
2018-03-25 13:47:33,479 [scala-execution-context-global-61]          TRACE k.grid.GridImp                       - Selecting actor at: akka.tcp://cm-well-mc-ppe@10.205.159.43:0/user/HealthActor-router
```
The console cannot connect to the HealthActor and thus gets null pointer exception.
