### ISSUE TITLE
STP Engine - IllegalStateException during sensor consuming data

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#600]
Following exception appears periodically during sensor consuming data from source
```
2018-03-27 06:31:33,558 [scala-execution-context-global-538]         ERROR cmwell.tools.data.utils.akka.Retry$  - [dealsjvdealjvname] error in consuming data bytes from response, paths=/data.thomsonreuters.com/2-01935b1637fe79792b40a705738086f31e89a11e5084dcd8a85aac91a10f0c54, err=java.lang.IllegalStateException: Substream Source cannot be materialized more than once
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:722)
        at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:732)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:554)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:676)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:724)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.create(ActorCell.scala:654)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nicklester** [comment]
Reverted Akka Http Library to 10.0.11 in #608

**Comment by yanpom** [comment]
Verified and Closed
