### ISSUE TITLE
Sync-Dc issue with creating a new dc process with missing prefix

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#603]
Trying to create a new dc agent using pe instance of cmwell using the following qp configuration in config:

`"qp" : "system.parent.parent_hierarchy:/data.thomsonreuters.com,type.rdf:DealsJVContent,ISJOINTVENTURE.JV:true"`

Due to the JV prefix being missing on the target environment the dc process fails.

Error in local dc/application.log:

``cmwell.dc.stream.MessagesTypesAndExceptions$GetIndexTimeException: Get index time failed. Data center ID dc3?qp=system.parent.parent_hierarchy:/data.thomsonreuters.com/,type.rdf:DealsJVContent,ISJOINTVENTURE.JV:true, using local machine localhost:Some(9000)
    at cmwell.dc.stream.DataCenterSyncManager.$anonfun$retrieveLocalLastIndexTimeForDataCenterId$3(DataCenterSyncManager.scala:525)
    at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:53)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
    at akka.actor.ActorCell.invoke(ActorCell.scala:559)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Exception: Cm-Well returned bad response: status: 500 reason: Internal Server Error body: <!DOCTYPE html>
<html lang="en">
   <head>
       <title>Error</title>
       <style>
           html, body, pre {
               margin: 0;
               padding: 0;
               font-family: Monaco, 'Lucida Console', monospace;
               background: #ECECEC;
           }
           h1 {
               margin: 0;
               background: #A31012;
               padding: 20px 45px;
               color: #fff;
               text-shadow: 1px 1px 1px rgba(0,0,0,.3);
               border-bottom: 1px solid #690000;
               font-size: 28px;
           }
           p#detail {
               margin: 0;
               padding: 15px 45px;
               background: #F5A0A0;
               border-top: 4px solid #D36D6D;
               color: #730000;
               text-shadow: 1px 1px 1px rgba(255,255,255,.3);
               font-size: 14px;
               border-bottom: 1px solid #BA7A7A;
           }
       </style>
   </head>
   <body>
       <h1>Oops, an error occurred</h1>

       <p id="detail">
           This exception has been logged with id <strong>77db56enh</strong>.
       </p>

   </body>
</html>

    at cmwell.dc.stream.DataCenterSyncManager.$anonfun$retrieveLocalLastIndexTimeForDataCenterId$3(DataCenterSyncManager.scala:522)
    ... 21 common frames omitted`

Error in local ws log:

`@77db7j2b0 - Internal server error, for (GET) [/proc/dc/dc21?qp=system.parent.parent_hierarchy:/data.thomsonreuters.com,type.rdf:DealsJVContent,ISJOINTVENTURE.JV:true&format=json&with-data] ->
play.api.UnexpectedException: Unexpected exception[UnretrievableIdentifierException: couldn't find the prefix: JV]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
    at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$1.applyOrElse(PlayRequestHandler.scala:289)
    at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$1.applyOrElse(PlayRequestHandler.scala:286)`

**Comment by e-orz** [comment]
No, it's related to dc-sync with qp.
Dc-Sync does a simple check to find out what the destination currently have. When using qp with missing prefix, this check fails and the sync doesn't start at all. It's a catch-22.

Should be documented somehow as a limitation of the dc-sync with qp, or to make some small change to dc-sync manager that **only in the case of a missing prefix** will consider the target system as not having any of the requested infotons to be sync and start from the beginning.
