### ISSUE TITLE
STP - adding new agent causes STP manager to shut down and stop all jobs

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#619]
Adding new agent to PPE (2 already running) . Following exception appears. manager shuts down and then restarted for a minute and shuts down again with same exception:
```
2018-04-10 11:08:27,707 m-well-ppe-akka.actor.default-dispatcher-58] ERROR c.t.d.sparql.SparqlProcessorManager  - Sparql triggered processor manager died during processing of Some(StartJob(JobRead([job: LBDperson, config name:None, sensors: LBDpersonorganization, LBDpersonperson-legal-professional, LBDpersonperson],true))). The exception was:
akka.actor.InvalidActorNameException: actor name [LBDperson-68ff875c] is not unique!
        at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
        at akka.actor.dungeon.Children.reserveChild(Children.scala:134)
        at akka.actor.dungeon.Children.reserveChild$(Children.scala:132)
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:433)
        at akka.actor.dungeon.Children.makeChild(Children.scala:272)
        at akka.actor.dungeon.Children.actorOf(Children.scala:44)
        at akka.actor.dungeon.Children.actorOf$(Children.scala:43)
        at akka.actor.ActorCell.actorOf(ActorCell.scala:433)
        at cmwell.tools.data.sparql.SparqlProcessorManager.handleStartJob(SparqlProcessorManager.scala:417)
        at cmwell.tools.data.sparql.SparqlProcessorManager$$anonfun$receive$2.applyOrElse(SparqlProcessorManager.scala:137)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cmwell.tools.data.sparql.SparqlProcessorManager.aroundReceive(SparqlProcessorManager.scala:108)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-04-10 11:08:27,707 m-well-ppe-akka.actor.default-dispatcher-58] WARN  c.t.d.sparql.SparqlProcessorManager  - SparqlProcessorManager died, stopping all running jobs
```

**Comment by nicklester** [comment]
Has not been reproduced, and cannot reproduce. Can re-open if we see this again
