### ISSUE TITLE
CW fails to get local ES cluster on intiliatization

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#621]
Sometimes (happened twice on PPE) during initialization, all (almost all) CW fail to get local ES cluster.
Below exception written in application log 
Nothing is written in stderr.log
Such exception should be written to stderr.log. There is a need to monitor such matter and restart CW in case it fails to get local ES cluster

```
2018-04-10 16:46:02,117 ticsearch[Kenneth Crichton][generic][T#311]] INFO  org.elasticsearch.client.transport   - [Kenneth Crichton] failed to get local cluster state for [10.204.146.166][oIpyU3ESQlqHMJXYtS9UMQ][<machinaName>][inet[/10.204.146.166:9302]]{rack_id=<nodeIP>, master=false}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [10.204.146.166][inet[/10.204.146.166:9302]][cluster:monitor/state] request_id [271350] timed out after [5001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by YoniMataraso** [comment]
@yanpom -does the CW recover from this?
