### ISSUE TITLE
STP -  Sparql triggered processor manager dies and fails to start because of timeout when trying to read token infoton

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#698]
Prod -  Sparql triggered processor manager died and fails to start because getting timeout to read configuration file with following exception

```
2018-05-23 11:30:09,174 -well-prod-akka.actor.default-dispatcher-82] INFO  c.t.d.sparql.SparqlProcessorManager  - starting sparql-processor manager instance on this machine
2018-05-23 11:31:09,176 m-well-prod-akka.actor.default-dispatcher-2] ERROR c.t.d.sparql.SparqlProcessorManager  - Sparql triggered processor manager died during processing of Some(StartJob(JobRead([job: persn, config name:None, sensors: personperson, personperson-legal-professional, personperson-legal-qualification],true))). The exception was:
java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
        at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
        at scala.concurrent.Await$.result(package.scala:142)
        at cmwell.tools.data.sparql.SparqlTriggeredProcessor.listen(SparqlTriggeredProcessor.scala:114)
        at cmwell.tools.data.sparql.SparqlTriggeredProcessor$.listen(SparqlTriggeredProcessor.scala:71)
        at cmwell.tools.data.sparql.SparqlProcessorManager.handleStartJob(SparqlProcessorManager.scala:434)
        at cmwell.tools.data.sparql.SparqlProcessorManager$$anonfun$receive$2.applyOrElse(SparqlProcessorManager.scala:133)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cmwell.tools.data.sparql.SparqlProcessorManager.aroundReceive(SparqlProcessorManager.scala:104)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-05-23 11:31:09,176 m-well-prod-akka.actor.default-dispatcher-2] WARN  c.t.d.sparql.SparqlProcessorManager  - SparqlProcessorManager died, stopping all running jobs

```

**Comment by nicklester** [comment]
This should now be resolved as this was a failure to read the token infoton. With zstore and retries this is resolved.

**Comment by yanpom** [comment]
Resolved
